services:
  web:
    image: d5avard/web:0.1.15
    ports:
      - "8080:80"
      - "8443:443"
    user: "webuser"
    environment:
      WEB_CERT_FILE: "/app/certs/fullchain.pem"
      WEB_KEY_FILE: "/app/certs/privkey.pem"
    volumes:
      - /Users/danysavard/Projects/factory/web/web/certs:/app/certs:ro
  db:
    container_name: postgres
    image: postgres:17.3-bookworm
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "factory"
      PGDATA: "/data"
    volumes:
    - ./data:/data
    ports:
    - 5432:5432

