services:
  web:
    image: d5avard/web:0.1.15
    ports:
      - "80:80"
      - "443:443"
    user: "webuser"
    environment:
      WEB_CERT_FILE: "/etc/letsencrypt/live/danysavard.ca/fullchain.pem"
      WEB_KEY_FILE: "/etc/letsencrypt/live/danysavard.ca/privkey.pem"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
