services:
  web:
    build: ./deployments/web/.
    ports:
      - "8080:80"
    user:  "webuser"
  db:
    container_name: postgres
    image: postgres:17.3-bookworm
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "factory"
      PGDATA: "/data"
    volumes:
    - ./data:/data
    ports:
    - 5432:5432

